export default [
    {
        path:"/mimy",
        name:"个人中心",
        component:()=>import("../views/mi-my.vue")
    },
    {
        path:"/login", 
        name:"登陆",
        component:()=>import("../components/my/login.vue")
    },
    {
        path:"/register",
        name:"注册",
        component:()=>import("../components/my/register.vue")
    },
    {
        path:"/address",
        name:"我的地址",
        component:()=>import("../components/my/address.vue")
    },
    {
        path:"/addressAdd",
        name:"添加地址",
        component:()=>import("../components/my/addressAdd.vue")
    },
    {
        path:"/addressEdit",
        name:"编辑地址",
        component:()=>import("../components/my/addressEdit.vue")
    },
    {
        path:"/coupon",
        name:"优惠券",
        component:()=>import("../components/my/coupon.vue")
    },
    {
        path:"/service",
        name:"服务",
        component:()=>import("../components/my/service.vue")
    },
    {
        path:"/collection",
        name:"收藏",
        component:()=>import("../components/my/collection.vue")
    },
    {
        path:"/caftersell",
        name:"售后记录",
        component:()=>import("../components/my/afterSell.vue")
    },
    {
        path:"/vipcenter",
        name:"会员中心",
        component:()=>import("../components/my/vipCenter.vue")
    },
    
]